config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  devise_for :users
  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end
  
  
  
  get 'welcome/index'

  get 'welcome/about'
  
  root 'users#user_home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  
  validates :name,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.name = name.titleize if name.present? }
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         #:confirmable  - stub confirmable out for ease of testing new users
         
  has_many :items
  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user! # redirect to login page if user not signed-in.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = current_user.items.build(item_params)
    
    if @item.save
      flash[:success] = "Item saved!"
      redirect_to current_user
    else
      flash[:alert] = "Item could not be saved."
      redirect_to :back
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    
    if @item.user == current_user
      @item.destroy
    end
    
    respond_to do |format|
      format.html
      format.js 
    end
  end

  private
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @name = @user.name
    @items = @user.items
    @item = Item.new
  end
  
  def user_home
    redirect_to current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def time_remaining(item)
    # return time diff between now and 7 days from when item was created.
    distance_of_time_in_words(item.created_at + (60*60*24*7), Time.now )+" left"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [@user, @item] do |f|  %>
  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter item name" %>
  </div>
  <%= f.submit "Save Item", class: 'btn btn-success' %>
<% end %>

app/views/items/_item.html.erb
<li id="js-item-<%= item.id %>"><%= item.name %>
  <% if item.user == current_user %>
    <%= link_to "", [item.user, item], method: :delete, class: 'glyphicon glyphicon-ok', remote: true %>
  <% end %>  
  <em><%= time_remaining(item) %></em>
</li>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
$('#js-item-<%= @item.id %>').hide();
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<ul class="nav nav-tabs">
    <li><%= link_to "Bloccitoff", welcome_index_path %></li>
    <li><%= link_to "About", welcome_about_path %></li>
    <div class = "pull-right user-nav-links">
        <% if user_signed_in? %>
            <li><%= link_to "My To-Do List", current_user %></li>
            <li class = "signed-in">Signed in as: <strong><%= current_user.name %></strong> </li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path  %> -
            <%= link_to "Sign In", new_user_session_path  %></li>
        <% end %>
    </div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>

  </div>

</body>
</html>

app/views/users/show.html.erb
<h1><%= @name %>'s Profile </h1>

<%= @name %>'s Email: <%= @user.email %>

<% if @user == current_user %>
  <h2> Add a To-Do Item</h2>
  <%= render 'items/form' %>
<% end %>

<h2>To Do:</h2>

<%= render @items %>

app/views/welcome/about.html.erb
<h1>Blocitoff App</h1>

app/views/welcome/index.html.erb
<h1>Welcome to the Bloccitoff To-Do List App!</h1>